repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
        types_or: [python, yaml, json, toml]
    -   id: trailing-whitespace
        types_or: [python, yaml, json, toml]
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-xml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
    -   id: ruff
        types_or: [ python, pyi ]
    -   id: ruff-format
        types_or: [ python, pyi ]

default_language_version:
    python: python3
