repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: end-of-file-fixer
        types_or: [python, yaml, json, toml]
    -   id: trailing-whitespace
        types_or: [python, yaml, json, toml]
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
