BPOD_BEHAVIOR_PORTS_ENABLED: [true, false, false, false]
BPOD_BNC_PORTS_ENABLED: [true, true]
PYBPOD_API_ACCEPT_STDIN:  true
PYBPOD_API_LOG_FILE: null
PYBPOD_API_LOG_LEVEL: null
PYBPOD_API_STREAM2STDOUT: false
PYBPOD_BOARD: _iblrig_mainenlab_ephys_0
PYBPOD_CREATOR: '["_iblrig_fake_user", "f092c2d5-c98a-45a1-be7c-df05f129a93c", "local"]'
PYBPOD_EXPERIMENT: _iblrig_tasks
PYBPOD_NET_PORT: 36000
PYBPOD_PROJECT: IBL
PYBPOD_PROTOCOL: _iblrig_tasks_biasedChoiceWorld
PYBPOD_SERIAL_PORT: COM#
PYBPOD_SESSION: "00010131-000001"
PYBPOD_SESSION_PATH: "C:\\iblrig_params\\IBL\\experiments\\_iblrig_tasks\\setups\\passiveChoiceWorld_testing\\sessions\\00010131-000001"
PYBPOD_SETUP:  fake_passiveChoiceWorld_testing
PYBPOD_SUBJECTS:  ["['_iblrig_fake_mouse', '57b50a6a-29e0-433f-ab82-53b776bfa1be']"]
PYBPOD_SUBJECT_EXTRA:  '"{"__UUID4__": "57b50a6a-29e0-433f-ab82-53b776bfa1be", "__DEF-URL__": "http://pybpod.readthedocs.org", "__DEF-TEXT__": "This file contains information about a subject used on PyBpod GUI.", "__SOFTWARE__": "PyBpod GUI API v1.2.1", "name": "_iblrig_fake_mouse", "setup": "None", "uuid4": "57b50a6a-29e0-433f-ab82-53b776bfa1be"}"'
PYBPOD_USER_EXTRA: '{"__UUID4__": "f092c2d5-c98a-45a1-be7c-df05f129a93c", "__DEF-URL__": "http://pybpod.readthedocs.org", "__DEF-TEXT__": "This file contains information about a user used on PyBpod GUI.", "__SOFTWARE__": "PyBpod GUI API v1.2.1"}'
PYBPOD_VARSNAMES: []
TARGET_BPOD_FIRMWARE_VERSION: "22"
