# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig/gui/ui_tab_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabAbout(object):
    def setupUi(self, TabAbout):
        TabAbout.setObjectName("TabAbout")
        TabAbout.resize(498, 559)
        self.gridLayout = QtWidgets.QGridLayout(TabAbout)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(87, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(186, 87, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 2)
        self.uiLabelLogo = QtWidgets.QLabel(TabAbout)
        self.uiLabelLogo.setMaximumSize(QtCore.QSize(90, 90))
        self.uiLabelLogo.setText("")
        self.uiLabelLogo.setPixmap(QtGui.QPixmap(":/images/iblrig_logo"))
        self.uiLabelLogo.setScaledContents(True)
        self.uiLabelLogo.setObjectName("uiLabelLogo")
        self.gridLayout.addWidget(self.uiLabelLogo, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(186, 87, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 2)
        self.uiLabelCopyright = QtWidgets.QLabel(TabAbout)
        self.uiLabelCopyright.setTextFormat(QtCore.Qt.MarkdownText)
        self.uiLabelCopyright.setAlignment(QtCore.Qt.AlignCenter)
        self.uiLabelCopyright.setObjectName("uiLabelCopyright")
        self.gridLayout.addWidget(self.uiLabelCopyright, 2, 0, 1, 5)
        spacerItem3 = QtWidgets.QSpacerItem(407, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(145, 157, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 0, 4, 1)
        self.commandLinkButtonGitHub = QtWidgets.QCommandLinkButton(TabAbout)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/github"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButtonGitHub.setIcon(icon)
        self.commandLinkButtonGitHub.setObjectName("commandLinkButtonGitHub")
        self.gridLayout.addWidget(self.commandLinkButtonGitHub, 4, 1, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(145, 157, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 4, 4, 1)
        self.commandLinkButtonDoc = QtWidgets.QCommandLinkButton(TabAbout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/help"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButtonDoc.setIcon(icon1)
        self.commandLinkButtonDoc.setObjectName("commandLinkButtonDoc")
        self.gridLayout.addWidget(self.commandLinkButtonDoc, 5, 1, 1, 3)
        self.commandLinkButtonDiscussion = QtWidgets.QCommandLinkButton(TabAbout)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/discussion"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButtonDiscussion.setIcon(icon2)
        self.commandLinkButtonDiscussion.setObjectName("commandLinkButtonDiscussion")
        self.gridLayout.addWidget(self.commandLinkButtonDiscussion, 6, 1, 1, 3)
        self.commandLinkButtonIssues = QtWidgets.QCommandLinkButton(TabAbout)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/bug"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButtonIssues.setIcon(icon3)
        self.commandLinkButtonIssues.setObjectName("commandLinkButtonIssues")
        self.gridLayout.addWidget(self.commandLinkButtonIssues, 7, 1, 1, 3)
        spacerItem6 = QtWidgets.QSpacerItem(407, 74, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 8, 0, 1, 5)
        self.uiLabelAnyDesk = QtWidgets.QLabel(TabAbout)
        self.uiLabelAnyDesk.setText("")
        self.uiLabelAnyDesk.setAlignment(QtCore.Qt.AlignCenter)
        self.uiLabelAnyDesk.setObjectName("uiLabelAnyDesk")
        self.gridLayout.addWidget(self.uiLabelAnyDesk, 9, 0, 1, 5)

        self.retranslateUi(TabAbout)
        QtCore.QMetaObject.connectSlotsByName(TabAbout)

    def retranslateUi(self, TabAbout):
        _translate = QtCore.QCoreApplication.translate
        TabAbout.setWindowTitle(_translate("TabAbout", "Form"))
        self.uiLabelCopyright.setText(_translate("TabAbout", "**IBLRIG v8.13.0**\n"
"\n"
"© 2024, International Brain Laboratory"))
        self.commandLinkButtonGitHub.setStatusTip(_translate("TabAbout", "Click to open the IBLRIG GitHub repository"))
        self.commandLinkButtonGitHub.setText(_translate("TabAbout", "&GitHub"))
        self.commandLinkButtonDoc.setStatusTip(_translate("TabAbout", "Click to open the IBLRIG documentation"))
        self.commandLinkButtonDoc.setText(_translate("TabAbout", "&Documentation"))
        self.commandLinkButtonDiscussion.setStatusTip(_translate("TabAbout", "Click to open the IBLRIG discussion board"))
        self.commandLinkButtonDiscussion.setText(_translate("TabAbout", "Discussion &Board"))
        self.commandLinkButtonIssues.setStatusTip(_translate("TabAbout", "Click to open the IBLRIG issue tracker"))
        self.commandLinkButtonIssues.setText(_translate("TabAbout", "&Issue Tracker"))
from iblrig.gui import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabAbout = QtWidgets.QWidget()
    ui = Ui_TabAbout()
    ui.setupUi(TabAbout)
    TabAbout.show()
    sys.exit(app.exec_())
