# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig\gui\ui_tab_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabLog(object):
    def setupUi(self, TabLog):
        TabLog.setObjectName("TabLog")
        TabLog.resize(619, 821)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(TabLog)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(12)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.widgetLog = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widgetLog.sizePolicy().hasHeightForWidth())
        self.widgetLog.setSizePolicy(sizePolicy)
        self.widgetLog.setObjectName("widgetLog")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetLog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxLog = QtWidgets.QGroupBox(self.widgetLog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBoxLog.sizePolicy().hasHeightForWidth())
        self.groupBoxLog.setSizePolicy(sizePolicy)
        self.groupBoxLog.setObjectName("groupBoxLog")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxLog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plainTextEditLog = QtWidgets.QPlainTextEdit(self.groupBoxLog)
        self.plainTextEditLog.setStyleSheet("QPlainTextEdit {background-color: rgb(0, 0, 0)};")
        self.plainTextEditLog.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEditLog.setReadOnly(True)
        self.plainTextEditLog.setObjectName("plainTextEditLog")
        self.verticalLayout_5.addWidget(self.plainTextEditLog)
        self.widget = QtWidgets.QWidget(self.groupBoxLog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFontSize = QtWidgets.QLabel(self.widget)
        self.labelFontSize.setObjectName("labelFontSize")
        self.horizontalLayout.addWidget(self.labelFontSize)
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.widget)
        self.spinBoxFontSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxFontSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxFontSize.setAccelerated(False)
        self.spinBoxFontSize.setMinimum(7)
        self.spinBoxFontSize.setMaximum(99)
        self.spinBoxFontSize.setProperty("value", 11)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.horizontalLayout.addWidget(self.spinBoxFontSize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonClipboard = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/clipboard"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClipboard.setIcon(icon)
        self.pushButtonClipboard.setObjectName("pushButtonClipboard")
        self.horizontalLayout.addWidget(self.pushButtonClipboard)
        self.verticalLayout_5.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.groupBoxLog)
        self.widgetNarrative = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetNarrative.sizePolicy().hasHeightForWidth())
        self.widgetNarrative.setSizePolicy(sizePolicy)
        self.widgetNarrative.setObjectName("widgetNarrative")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetNarrative)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupsBoxNarrative = QtWidgets.QGroupBox(self.widgetNarrative)
        self.groupsBoxNarrative.setObjectName("groupsBoxNarrative")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupsBoxNarrative)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEditNarrative = QtWidgets.QPlainTextEdit(self.groupsBoxNarrative)
        self.plainTextEditNarrative.setObjectName("plainTextEditNarrative")
        self.verticalLayout_4.addWidget(self.plainTextEditNarrative)
        self.verticalLayout_3.addWidget(self.groupsBoxNarrative)
        self.verticalLayout.addWidget(self.splitter)
        self.labelFontSize.setBuddy(self.spinBoxFontSize)

        self.retranslateUi(TabLog)
        QtCore.QMetaObject.connectSlotsByName(TabLog)

    def retranslateUi(self, TabLog):
        _translate = QtCore.QCoreApplication.translate
        TabLog.setWindowTitle(_translate("TabLog", "Form"))
        self.groupBoxLog.setTitle(_translate("TabLog", "Session Log"))
        self.labelFontSize.setStatusTip(_translate("TabLog", "Set the log\'s font size"))
        self.labelFontSize.setText(_translate("TabLog", "&Font Size"))
        self.spinBoxFontSize.setStatusTip(_translate("TabLog", "Set the log\'s font size"))
        self.pushButtonClipboard.setStatusTip(_translate("TabLog", "Copy log to clipboard"))
        self.pushButtonClipboard.setText(_translate("TabLog", " &Copy"))
        self.groupsBoxNarrative.setTitle(_translate("TabLog", "Session Narrative"))
        self.plainTextEditNarrative.setPlaceholderText(_translate("TabLog", "Enter your obvservations here ..."))
from iblrig.gui import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabLog = QtWidgets.QWidget()
    ui = Ui_TabLog()
    ui.setupUi(TabLog)
    TabLog.show()
    sys.exit(app.exec_())
