# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig\gui\ui_tab_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabLog(object):
    def setupUi(self, TabLog):
        TabLog.setObjectName("TabLog")
        TabLog.resize(607, 766)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEditLog = QtWidgets.QPlainTextEdit(TabLog)
        self.plainTextEditLog.setStyleSheet("QPlainTextEdit {background-color: rgb(0, 0, 0)};")
        self.plainTextEditLog.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEditLog.setReadOnly(True)
        self.plainTextEditLog.setObjectName("plainTextEditLog")
        self.verticalLayout.addWidget(self.plainTextEditLog)
        self.widget = QtWidgets.QWidget(TabLog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFontSize = QtWidgets.QLabel(self.widget)
        self.labelFontSize.setObjectName("labelFontSize")
        self.horizontalLayout.addWidget(self.labelFontSize)
        self.spinBoxFontSize = QtWidgets.QSpinBox(self.widget)
        self.spinBoxFontSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxFontSize.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxFontSize.setAccelerated(False)
        self.spinBoxFontSize.setMinimum(7)
        self.spinBoxFontSize.setMaximum(99)
        self.spinBoxFontSize.setProperty("value", 11)
        self.spinBoxFontSize.setObjectName("spinBoxFontSize")
        self.horizontalLayout.addWidget(self.spinBoxFontSize)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonClipboard = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/clipboard"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClipboard.setIcon(icon)
        self.pushButtonClipboard.setObjectName("pushButtonClipboard")
        self.horizontalLayout.addWidget(self.pushButtonClipboard)
        self.verticalLayout.addWidget(self.widget)
        self.labelFontSize.setBuddy(self.spinBoxFontSize)

        self.retranslateUi(TabLog)
        QtCore.QMetaObject.connectSlotsByName(TabLog)

    def retranslateUi(self, TabLog):
        _translate = QtCore.QCoreApplication.translate
        TabLog.setWindowTitle(_translate("TabLog", "Form"))
        self.labelFontSize.setStatusTip(_translate("TabLog", "Set the log\'s font size"))
        self.labelFontSize.setText(_translate("TabLog", "&Font Size"))
        self.spinBoxFontSize.setStatusTip(_translate("TabLog", "Set the log\'s font size"))
        self.pushButtonClipboard.setStatusTip(_translate("TabLog", "Copy log to clipboard"))
        self.pushButtonClipboard.setText(_translate("TabLog", " &Copy"))
from iblrig.gui import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabLog = QtWidgets.QWidget()
    ui = Ui_TabLog()
    ui.setupUi(TabLog)
    TabLog.show()
    sys.exit(app.exec_())
