# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig/gui/ui_tab_data.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabData(object):
    def setupUi(self, TabData):
        TabData.setObjectName("TabData")
        TabData.resize(522, 678)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabData)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(TabData)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)

        self.retranslateUi(TabData)
        QtCore.QMetaObject.connectSlotsByName(TabData)

    def retranslateUi(self, TabData):
        _translate = QtCore.QCoreApplication.translate
        TabData.setWindowTitle(_translate("TabData", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabData = QtWidgets.QWidget()
    ui = Ui_TabData()
    ui.setupUi(TabData)
    TabData.show()
    sys.exit(app.exec_())
