# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig/gui/ui_tab_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabLog(object):
    def setupUi(self, TabLog):
        TabLog.setObjectName("TabLog")
        TabLog.resize(607, 766)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabLog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEditLog = QtWidgets.QPlainTextEdit(TabLog)
        self.plainTextEditLog.setStyleSheet("QPlainTextEdit { background-color: rgb(0, 0, 0) }")
        self.plainTextEditLog.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEditLog.setReadOnly(True)
        self.plainTextEditLog.setObjectName("plainTextEditLog")
        self.verticalLayout.addWidget(self.plainTextEditLog)
        self.widget = QtWidgets.QWidget(TabLog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonClipboard = QtWidgets.QPushButton(self.widget)
        self.pushButtonClipboard.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButtonClipboard.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/clipboard"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClipboard.setIcon(icon)
        self.pushButtonClipboard.setObjectName("pushButtonClipboard")
        self.horizontalLayout.addWidget(self.pushButtonClipboard)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(TabLog)
        QtCore.QMetaObject.connectSlotsByName(TabLog)

    def retranslateUi(self, TabLog):
        _translate = QtCore.QCoreApplication.translate
        TabLog.setWindowTitle(_translate("TabLog", "Form"))
        self.pushButtonClipboard.setStatusTip(_translate("TabLog", "Copy log to clipboard"))
from iblrig.gui import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabLog = QtWidgets.QWidget()
    ui = Ui_TabLog()
    ui.setupUi(TabLog)
    TabLog.show()
    sys.exit(app.exec_())
