# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig/gui/ui_tab_docs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabDocs(object):
    def setupUi(self, TabDocs):
        TabDocs.setObjectName("TabDocs")
        TabDocs.resize(706, 695)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabDocs)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(TabDocs)
        self.webEngineView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.webEngineView.setAcceptDrops(False)
        self.webEngineView.setProperty("url", QtCore.QUrl("https://int-brain-lab.github.io/iblrig/"))
        self.webEngineView.setProperty("zoomFactor", 0.9)
        self.webEngineView.setObjectName("webEngineView")
        self.verticalLayout.addWidget(self.webEngineView)
        self.line = QtWidgets.QFrame(TabDocs)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame = QtWidgets.QFrame(TabDocs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.uiPushWebBack = QtWidgets.QPushButton(self.frame)
        self.uiPushWebBack.setEnabled(False)
        self.uiPushWebBack.setMaximumSize(QtCore.QSize(24, 16777215))
        self.uiPushWebBack.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/previous"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPushWebBack.setIcon(icon)
        self.uiPushWebBack.setObjectName("uiPushWebBack")
        self.horizontalLayout_5.addWidget(self.uiPushWebBack)
        self.uiPushWebForward = QtWidgets.QPushButton(self.frame)
        self.uiPushWebForward.setEnabled(False)
        self.uiPushWebForward.setMaximumSize(QtCore.QSize(24, 16777215))
        self.uiPushWebForward.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/next"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPushWebForward.setIcon(icon1)
        self.uiPushWebForward.setObjectName("uiPushWebForward")
        self.horizontalLayout_5.addWidget(self.uiPushWebForward)
        self.uiPushWebHome = QtWidgets.QPushButton(self.frame)
        self.uiPushWebHome.setMaximumSize(QtCore.QSize(24, 16777215))
        self.uiPushWebHome.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/home"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPushWebHome.setIcon(icon2)
        self.uiPushWebHome.setIconSize(QtCore.QSize(16, 16))
        self.uiPushWebHome.setObjectName("uiPushWebHome")
        self.horizontalLayout_5.addWidget(self.uiPushWebHome)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.uiPushWebBrowser = QtWidgets.QPushButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/globe"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiPushWebBrowser.setIcon(icon3)
        self.uiPushWebBrowser.setObjectName("uiPushWebBrowser")
        self.horizontalLayout_5.addWidget(self.uiPushWebBrowser)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(TabDocs)
        QtCore.QMetaObject.connectSlotsByName(TabDocs)

    def retranslateUi(self, TabDocs):
        _translate = QtCore.QCoreApplication.translate
        TabDocs.setWindowTitle(_translate("TabDocs", "Form"))
        self.uiPushWebBack.setStatusTip(_translate("TabDocs", "Click to go back"))
        self.uiPushWebForward.setStatusTip(_translate("TabDocs", "Click to go forward"))
        self.uiPushWebHome.setStatusTip(_translate("TabDocs", "Click to go to home page"))
        self.uiPushWebBrowser.setStatusTip(_translate("TabDocs", "Click to open the current page in your web browser"))
        self.uiPushWebBrowser.setText(_translate("TabDocs", " Open in Browser"))
from PyQt5 import QtWebEngineWidgets
from iblrig.gui import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabDocs = QtWidgets.QWidget()
    ui = Ui_TabDocs()
    ui.setupUi(TabDocs)
    TabDocs.show()
    sys.exit(app.exec_())
