# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig\gui\ui_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update(object):
    def setupUi(self, update):
        update.setObjectName("update")
        update.resize(451, 496)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(update.sizePolicy().hasHeightForWidth())
        update.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iblrig\\gui\\wizard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        update.setWindowIcon(icon)
        update.setModal(True)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(update)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiLayoutLogo = QtWidgets.QVBoxLayout()
        self.uiLayoutLogo.setContentsMargins(-1, -1, 6, -1)
        self.uiLayoutLogo.setObjectName("uiLayoutLogo")
        self.uiLabelLogo = QtWidgets.QLabel(update)
        self.uiLabelLogo.setMaximumSize(QtCore.QSize(64, 64))
        self.uiLabelLogo.setText("")
        self.uiLabelLogo.setPixmap(QtGui.QPixmap(":/images/iblrig_logo"))
        self.uiLabelLogo.setScaledContents(True)
        self.uiLabelLogo.setObjectName("uiLabelLogo")
        self.uiLayoutLogo.addWidget(self.uiLabelLogo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.uiLayoutLogo.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.uiLayoutLogo)
        self.uiLayoutRight = QtWidgets.QVBoxLayout()
        self.uiLayoutRight.setObjectName("uiLayoutRight")
        self.uiLabelHeader = QtWidgets.QLabel(update)
        self.uiLabelHeader.setObjectName("uiLabelHeader")
        self.uiLayoutRight.addWidget(self.uiLabelHeader)
        self.uiTextBrowserChanges = QtWidgets.QTextBrowser(update)
        self.uiTextBrowserChanges.setSizeIncrement(QtCore.QSize(0, 0))
        self.uiTextBrowserChanges.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.uiTextBrowserChanges.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.uiTextBrowserChanges.setMarkdown("")
        self.uiTextBrowserChanges.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.uiTextBrowserChanges.setObjectName("uiTextBrowserChanges")
        self.uiLayoutRight.addWidget(self.uiTextBrowserChanges)
        self.uiLabelFooter = QtWidgets.QLabel(update)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiLabelFooter.sizePolicy().hasHeightForWidth())
        self.uiLabelFooter.setSizePolicy(sizePolicy)
        self.uiLabelFooter.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.uiLabelFooter.setWordWrap(True)
        self.uiLabelFooter.setObjectName("uiLabelFooter")
        self.uiLayoutRight.addWidget(self.uiLabelFooter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.uiLayoutRight.addItem(spacerItem1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(update)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 37))
        self.plainTextEdit.setStyleSheet("background-color: rgb(1, 36, 86);\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.uiLayoutRight.addWidget(self.plainTextEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.uiLayoutRight.addItem(spacerItem2)
        self.uiLine = QtWidgets.QFrame(update)
        self.uiLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.uiLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.uiLine.setObjectName("uiLine")
        self.uiLayoutRight.addWidget(self.uiLine)
        self.uiLayoutButton = QtWidgets.QHBoxLayout()
        self.uiLayoutButton.setObjectName("uiLayoutButton")
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uiLayoutButton.addItem(spacerItem3)
        self.uiPushButtonOK = QtWidgets.QPushButton(update)
        self.uiPushButtonOK.setObjectName("uiPushButtonOK")
        self.uiLayoutButton.addWidget(self.uiPushButtonOK)
        self.uiLayoutRight.addLayout(self.uiLayoutButton)
        self.horizontalLayout_2.addLayout(self.uiLayoutRight)
        self.horizontalLayout_2.setStretch(1, 100)

        self.retranslateUi(update)
        self.uiPushButtonOK.released.connect(update.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(update)

    def retranslateUi(self, update):
        _translate = QtCore.QCoreApplication.translate
        update.setWindowTitle(_translate("update", "Update Notice"))
        self.uiLabelHeader.setText(_translate("update", "Update Available!"))
        self.uiLabelFooter.setText(_translate("update", "To update, close IBL Rig Wizard and run the following commands within the iblrigv8 Python environment:"))
        self.plainTextEdit.setPlainText(_translate("update", "git pull\n"
"pip install --upgrade -e ."))
        self.uiPushButtonOK.setText(_translate("update", "OK"))
from iblrig.gui import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    update = QtWidgets.QDialog()
    ui = Ui_update()
    ui.setupUi(update)
    update.show()
    sys.exit(app.exec_())
