# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig\gui\ui_validation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_validation(object):
    def setupUi(self, validation):
        validation.setObjectName("validation")
        validation.setWindowModality(QtCore.Qt.ApplicationModal)
        validation.resize(500, 357)
        self.verticalLayout = QtWidgets.QVBoxLayout(validation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(validation)
        self.treeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setProperty("showDropIndicator", False)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeView.setAllColumnsShowFocus(True)
        self.treeView.setWordWrap(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.treeView.header().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonRerun = QtWidgets.QPushButton(validation)
        self.pushButtonRerun.setEnabled(False)
        self.pushButtonRerun.setObjectName("pushButtonRerun")
        self.horizontalLayout.addWidget(self.pushButtonRerun)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonOK = QtWidgets.QPushButton(validation)
        self.pushButtonOK.setDefault(True)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(validation)
        QtCore.QMetaObject.connectSlotsByName(validation)

    def retranslateUi(self, validation):
        _translate = QtCore.QCoreApplication.translate
        validation.setWindowTitle(_translate("validation", "System Validation"))
        self.pushButtonRerun.setText(_translate("validation", "Rerun"))
        self.pushButtonOK.setText(_translate("validation", "Close"))
from iblrig.gui import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    validation = QtWidgets.QDialog()
    ui = Ui_validation()
    ui.setupUi(validation)
    validation.show()
    sys.exit(app.exec_())
