# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig\gui\ui_valve.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_valve(object):
    def setupUi(self, valve):
        valve.setObjectName("valve")
        valve.resize(656, 425)
        self.verticalLayout = QtWidgets.QVBoxLayout(valve)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(valve)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxScale = QtWidgets.QGroupBox(self.widget)
        self.groupBoxScale.setEnabled(False)
        self.groupBoxScale.setObjectName("groupBoxScale")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxScale)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBoxScale)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalFrame = QtWidgets.QFrame(self.groupBoxScale)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditGrams = QtWidgets.QLineEdit(self.horizontalFrame)
        self.lineEditGrams.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditGrams.setReadOnly(True)
        self.lineEditGrams.setObjectName("lineEditGrams")
        self.horizontalLayout_2.addWidget(self.lineEditGrams)
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalFrame)
        self.label_3 = QtWidgets.QLabel(self.groupBoxScale)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.radioButtonStable = QtWidgets.QRadioButton(self.groupBoxScale)
        self.radioButtonStable.setMouseTracking(False)
        self.radioButtonStable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButtonStable.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.radioButtonStable.setText("")
        self.radioButtonStable.setObjectName("radioButtonStable")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButtonStable)
        self.verticalLayout_3.addWidget(self.groupBoxScale)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.groupBox = QtWidgets.QGroupBox(valve)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uiPlot = PlotWidget(self.frame)
        self.uiPlot.setObjectName("uiPlot")
        self.verticalLayout_2.addWidget(self.uiPlot)
        self.horizontalLayout_3.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(valve)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(valve)
        QtCore.QMetaObject.connectSlotsByName(valve)

    def retranslateUi(self, valve):
        _translate = QtCore.QCoreApplication.translate
        valve.setWindowTitle(_translate("valve", "Valve Calibration"))
        self.groupBoxScale.setTitle(_translate("valve", "Scale"))
        self.label.setText(_translate("valve", "Reading"))
        self.lineEditGrams.setPlaceholderText(_translate("valve", "0.00"))
        self.label_2.setText(_translate("valve", "g"))
        self.label_3.setText(_translate("valve", "Stable"))
        self.groupBox.setTitle(_translate("valve", "Calibration Values"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    valve = QtWidgets.QDialog()
    ui = Ui_valve()
    ui.setupUi(valve)
    valve.show()
    sys.exit(app.exec_())
