# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iblrig\gui\ui_valve.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_valve(object):
    def setupUi(self, valve):
        valve.setObjectName("valve")
        valve.resize(518, 311)
        self.verticalLayout = QtWidgets.QVBoxLayout(valve)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(valve)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout.addWidget(self.groupBox)
        self.frame = QtWidgets.QFrame(valve)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uiPlot = PlotWidget(self.frame)
        self.uiPlot.setObjectName("uiPlot")
        self.verticalLayout_2.addWidget(self.uiPlot)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(valve)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(valve)
        QtCore.QMetaObject.connectSlotsByName(valve)

    def retranslateUi(self, valve):
        _translate = QtCore.QCoreApplication.translate
        valve.setWindowTitle(_translate("valve", "Dialog"))
        self.groupBox.setTitle(_translate("valve", "GroupBox"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    valve = QtWidgets.QDialog()
    ui = Ui_valve()
    ui.setupUi(valve)
    valve.show()
    sys.exit(app.exec_())
