name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - iblrigv8
    paths:
      - '.github/workflows/documentation.yaml'
      - 'docs/**'
      - 'iblrig/__init__.py'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'pyproject.toml'
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --no-default-groups --group doc
      - name: Install PortAudio and GraphViz
        run: sudo apt-get install -y libportaudio2 graphviz
      - name: Sphinx build
        run: uv run --frozen sphinx-build docs/source docs/build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
