name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --no-default-groups --group doc
      - name: Sphinx build
        run: uv run --frozen sphinx-build docs/source docs/build/html
      - name: Build PDF
        run: uv run --frozen make -C docs/ simplepdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/simplepdf/*.pdf
          retention-days: 1

  release:
    name: Publish GitHub Release
    needs: pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
      - uses: softprops/action-gh-release@v2
        with:
          files: iblrig_*_reference.pdf
